# Generated by Django 4.2.15 on 2024-08-22 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calisanlar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calisan',
            name='yas',
        ),
        migrations.AddField(
            model_name='calisan',
            name='dogumtarihi',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='calisan',
            name='mail',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='calisan',
            name='sehir',
            field=models.CharField(default='Girilmedi', max_length=100),
        ),
        migrations.AddField(
            model_name='calisan',
            name='telefon',
            field=models.CharField(default='000 000 00 00', max_length=15),
        ),
        migrations.AddField(
            model_name='calisan',
            name='telefonturu',
            field=models.CharField(default='Girilmedi', max_length=100),
        ),
        migrations.AlterField(
            model_name='calisan',
            name='departman',
            field=models.CharField(default='Girilmedi', max_length=100),
        ),
        migrations.AlterField(
            model_name='calisan',
            name='maas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
