# Generated by Django 4.2.15 on 2024-08-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calisanlar', '0008_alter_calisan_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calisan',
            name='id',
        ),
        migrations.AddField(
            model_name='calisan',
            name='calisanid',
            field=models.CharField(default='default_value', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calisan',
            name='mail',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True, verbose_name='mail'),
        ),
    ]
