# Generated by Django 4.2.15 on 2024-08-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calisanlar', '0009_remove_calisan_id_calisan_calisanid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calisan',
            name='mail',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
